spring:
  application:
    name: horse racing management


# EMAIL SENDER
  mail:
    from: dangkhanh1130@gmail.com 
    host: smtp.gmail.com
    port: 587
    username: dangkhanh1130@gmail.com
    password: gwbecgplqiltlqxt

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




  datasource:
    url: jdbc:mysql://localhost:3306/horse_racing_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
# doi ten password theo mysql cua minh
  jpa:
    hibernate:
      ddl-auto: update

#    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  server:
    port: 8080


  data:
    redis:
      host: localhost
      port: 6379


  security:
    user:
      name: user
      password: 123




jwt:
  signerKey: ${SIGNERKEY}
  expiration: 604800000


outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: http://localhost:5173/authenticate


cloudinary:
  cloud-name: dzz3kbuuj
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: GP96QN61
    secretKey: GUMW05M4KQ6QLB5T9Y9X48OAWDZO70E7
    returnUrl: http://localhost:8080/api/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
